theme: jekyll-theme-minimal
title: 'PacBio Iso-Seq Workshop Online'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Using Slack in this workshop
    url: base/slack
  - title: Using Zoom in this workshop
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software

  - heading: Talks
  - title: Perspective on Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_PB.pdf
  - title: Iso-Seq Library Prep
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/Kristin_Mars_Library_Prep.pdf

  - heading: Prerequisites
  - title: Logging In
    url: intro/logging-in
  - title: CLI
    url: intro/command-line-intro
  - title: Cluster Computing
    url: intro/cluster


  - heading: Data Reduction
  - title: PacBio data
    url: pacbio_data/pacbio_data

  - heading: Dr. Liz Tseng
  - title: Introduction to PacBio and Iso-Seq
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/liz/1-Liz-Intro-to-PacBio-and-IsoSeq-2021.pdf
  - title: Using the Iso-Seq Application on SMRT Link and BioConda
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/liz/2-Liz-IsoSeq-with-SL-and-BioConda-2021.pdf
  - title: Tutorial
    url: https://github.com/Magdoll/cDNA_Cupcake/wiki/Iso-Seq-Bioinformatics-Tutorial

  - heading: Richard Kuo
  - title:  Transcriptome Annotation by Modular Algorithms TAMA
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/richard/uc_davis_isoseq_workshop_tama_v1.pdf
  - title: Tutorial
    url: ./pdfs/uc_davis_isoseq_workshop_tama_v1.pdf

  - heading: Fairlie Reese
  - title: Long-read RNA-seq transcriptomic analysis with TALON and Swan
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/Fairlie_210830_ucd_workshop.pdf
  - title: Tutorial
    url: ./fairlie/swan
  - title: Download ipython notebook
    url: https://raw.githubusercontent.com/fairliereese/210830_ucd_workshop/master/swan.ipynb

  - heading: Conesa Lab
  - title: IsoAnnot and IsoAnnotLite
    url: ./canesa/FIT
  - title: TappAS Install
    url: ./canesa/TappAS_install
  - title: Hands-on tappAS
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/isoseq/consealab/5.tappAS_HO.pdf

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-August-Iso-Seq
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
  - title: Pacific Biosciences website
    url: https://www.pacb.com/
  - title: Conesa lab website
    url: http://conesalab.org
